fix: current texts
Signed-off-by: Leandro Mendes <lmendes@redhat.com>

diff --git a/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml b/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
--- a/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
+++ b/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
@@ -167,7 +167,9 @@ spec:
         process_component() { # Expected argument is [component json]
             set -x
             COMPONENT=$1
-            PULLSPEC=$(jq -er '.containerImage' <<< "${COMPONENT}")
+            PULLSPEC=$(jq -er '.containerImage' <<< "${COMPONENT}") \
+                  || (echo "Missing containerImage for component." && exit 1 )
+
             DESTINATION="${DISK_IMAGE_DIR}/$(jq -er '.staged.destination' <<< "${COMPONENT}")/FILES" \
               || (echo "Missing staged.destination value for component. This should be an existing pulp repo. \
                   Failing" && exit 1)
@@ -182,8 +184,10 @@ spec:
             NUM_MAPPED_FILES=$(jq '.staged.files | length' <<< "${COMPONENT}")
             for ((i = 0; i < NUM_MAPPED_FILES; i++)) ; do
                 FILE=$(jq -c --arg i "$i" '.staged.files[$i|tonumber]' <<< "$COMPONENT")
-                SOURCE=$(jq -er '.source' <<< "$FILE")
-                FILENAME=$(jq -er '.filename' <<< "$FILE")
+                SOURCE=$(jq -er '.source' <<< "$FILE") \
+                  || (echo "Missing staged.files.source for component." && exit 1 )
+                FILENAME=$(jq -er '.filename' <<< "$FILE") \
+                  || (echo "Missing staged.files.filename for component." && exit 1 )
                 # The .qcow2 images are not zipped
                 if [ -f "${SOURCE}.gz" ] ; then
                     gzip -d "${SOURCE}.gz"
@@ -212,7 +216,7 @@ spec:
             while (( ${RUNNING_JOBS@P} >= $(params.concurrentLimit) )); do
                 wait -n
             done
-            process_component "$COMPONENT" 2> "$STDERR_FILE" &
+            process_component "$COMPONENT" > "$STDERR_FILE" &
         done
 
         # Wait for remaining processes to finish
@@ -720,7 +724,6 @@ spec:
 
         # get all of the signed binaries into a common directory
         CONTENT_DIR=/shared/artifacts
-        find $CONTENT_DIR
         SIGNED_DIR="$CONTENT_DIR/signed"
         mkdir -p "$SIGNED_DIR"
         mkdir -p "$CONTENT_DIR"/linux
@@ -853,10 +856,9 @@ spec:
             if [ "$err" -eq 0 ] ; then
                 echo -n "Success" > "$(results.result.path)"
             else
-                echo "$0: ERROR '$command' failed at line $line - exited with status $err" \
-                  > "$(results.result.path)"
+                echo "$0: ERROR '$command' failed at line $line - exited with status $err" > "$(results.result.path)"
                 if [ -f "$STDERR_FILE" ] ; then
-                    tail -n 20 "$STDERR_FILE" >> "$(results.result.path)"
+                    tail -n 20 "$STDERR_FILE" | tee -a "$(results.result.path)"
                 fi
             fi
             exit 0 # exit the script cleanly as there is no point in proceeding past an error or exit call
@@ -899,22 +901,21 @@ spec:
             return
           fi
 
-          # using { ;} to avoid subshell
           productName="$(jq -er '.productName' <<< "${contentGatewayConfig}")" \
-            || { echo "Missing contentGateway.productName value for component. This should be an existing product \
-                  in the Developer Portal. Failing" && exit 1; }
+           || ( echo "Missing contentGateway.productName value for component. This should be an existing product" \
+                      "in the Developer Portal. Failing" && exit 1 )
 
           productCode="$(jq -er '.productCode' <<< "${contentGatewayConfig}")" \
-            || { echo "Missing contentGateway.productCode value for component. This should be an existing product \
-                  in the Developer Portal. Failing" && exit 1; }
+           || ( echo "Missing contentGateway.productCode value for component. This should be an existing product" \
+                     "in the Developer Portal. Failing" && exit 1 )
 
           productVersionName="$(jq -er '.productVersionName' <<< "${contentGatewayConfig}")" \
-            || { echo "Missing contentGateway.productVersionName value for component. This should be an existing \
-                  product in the Developer Portal. Failing" && exit 1; }
+          || ( echo "Missing contentGateway.productVersionName value for component. This should be an existing" \
+                    "product in the Developer Portal. Failing" && exit 1 )
 
           filePrefix="$(jq -er '.filePrefix' <<< "${contentGatewayConfig}")" \
-            || { echo "Missing contentGateway.filePrefix value for component. This should be the prefix for files to \
-                  upload to the Developer Portal. Failing" && exit 1; }
+          || ( echo "Missing contentGateway.filePrefix value for component. This should be the prefix for files to" \
+                    "upload to the Developer Portal. Failing" && exit 1 )
 
           developer_portal_wrapper --debug --product-name "${productName}" \
             --product-code "${productCode}" \
@@ -966,5 +967,6 @@ spec:
         NUM_COMPONENTS=$(jq '.components | length' <<< "$SNAPSHOT_JSON")
         for ((i = 0; i < NUM_COMPONENTS; i++)) ; do
             COMPONENT=$(jq -c --arg i "$i" '.components[$i|tonumber]' <<< "$SNAPSHOT_JSON")
-            process_component_for_developer_portal "$COMPONENT" "${component_destinations[$i]}"  2> "$STDERR_FILE"
+            # eventually the function does not redirect the error to stderr, so looking for all output
+            process_component_for_developer_portal "$COMPONENT" "${component_destinations[$i]}" @> "$STDERR_FILE"
         done
